using System.Globalization;
using GearGauge.UI.Settings;

namespace GearGauge.UI.Localization;

public sealed class UiLocalizer
{
    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Dictionaries =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["zh-CN"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["AppTitle"] = "GearGauge",
                ["MonitorTab"] = "监控",
                ["SettingsTab"] = "设置",
                ["OverlayTab"] = "飘窗",
                ["Monitoring"] = "监控",
                ["Settings"] = "设置",
                ["LastUpdatedPrefix"] = "最后更新",
                ["Initializing"] = "正在初始化监控服务...",
                ["MonitoringActive"] = "监控已启动。",
                ["InitializationFailed"] = "初始化失败",
                ["RefreshFailed"] = "刷新失败",
                ["LastAttempt"] = "最后尝试",
                ["Stopping"] = "正在停止监控服务...",
                ["SourcePrefix"] = "来源",
                ["Elevated"] = "已提权",
                ["NotElevated"] = "未以管理员运行，部分传感器不可用",
                ["RestartAsAdmin"] = "以管理员重新启动",
                ["CpuSection"] = "处理器",
                ["GpuSection"] = "显卡",
                ["MemorySection"] = "内存",
                ["FpsSection"] = "帧率",
                ["NetworkSection"] = "网络",
                ["PerCoreMetrics"] = "核心指标",
                ["Usage"] = "使用率",
                ["Temperature"] = "温度",
                ["Power"] = "功耗",
                ["Clock"] = "频率",
                ["Capacity"] = "容量",
                ["Used"] = "已用",
                ["Available"] = "可用",
                ["Display"] = "显示输出",
                ["Game"] = "游戏",
                ["Active"] = "当前内容",
                ["DisplayName"] = "显示器",
                ["Provider"] = "来源",
                ["Status"] = "状态",
                ["Model"] = "型号",
                ["SettingsSampling"] = "采样",
                ["SettingsLanguage"] = "语言",
                ["SettingsTheme"] = "主题",
                ["SettingsTemperatureUnit"] = "温度单位",
                ["SettingsGpuSelection"] = "监控显卡",
                ["SettingsNetworkSelection"] = "监控网卡",
                ["SettingsMetricGpuSelection"] = "GPU 指标来源",
                ["SettingsMetricNetworkSelection"] = "网卡指标来源",
                ["SettingsPercentages"] = "百分比",
                ["SettingsTemperatures"] = "温度",
                ["SettingsClocks"] = "频率",
                ["SettingsPowerMemory"] = "功耗与内存",
                ["SettingsNetwork"] = "网络",
                ["SampleIntervalMs"] = "采样间隔（毫秒）",
                ["CpuUsageDecimals"] = "CPU 使用率小数位",
                ["GpuUsageDecimals"] = "GPU 使用率小数位",
                ["MemoryUsageDecimals"] = "内存使用率小数位",
                ["CpuTemperatureDecimals"] = "CPU 温度小数位",
                ["GpuTemperatureDecimals"] = "GPU 温度小数位",
                ["CpuClock"] = "CPU 频率",
                ["GpuClock"] = "GPU 频率",
                ["CpuPowerDecimals"] = "CPU 功耗小数位",
                ["GpuPowerDecimals"] = "GPU 功耗小数位",
                ["MemoryCapacityDecimals"] = "内存容量小数位",
                ["NetworkSpeed"] = "网速单位",
                ["UnitLabel"] = "单位",
                ["DecimalsLabel"] = "小数位数",
                ["Save"] = "保存",
                ["Cancel"] = "取消",
                ["AllDevices"] = "全部",
                ["LanguageSystem"] = "跟随系统",
                ["LanguageChinese"] = "中文",
                ["LanguageEnglish"] = "英文",
                ["ThemeSystem"] = "跟随系统",
                ["ThemeLight"] = "浅色",
                ["ThemeDark"] = "深色",
                ["TempCelsius"] = "摄氏度",
                ["TempFahrenheit"] = "华氏度",
                ["Download"] = "下载",
                ["Upload"] = "上传",
                ["Core"] = "核心",
                ["ActiveState"] = "活动",
                ["IdleState"] = "空闲",
                ["Up"] = "已连接",
                ["Down"] = "已断开",
                ["SelectedBadge"] = "已选中",
                ["SettingsSystem"] = "系统",
                ["SettingsAutoStart"] = "开机自启动",
                ["SettingsCloseToTray"] = "关闭时最小化到系统托盘",
                ["TrayShowWindow"] = "打开主界面",
                ["TrayTaskPage"] = "任务页面",
                ["TrayExit"] = "退出",
                ["SaveSuccess"] = "设置已保存",
                ["SettingsOverlay"] = "飘窗",
                ["OverlayEnabled"] = "启用飘窗",
                ["OverlayEdge"] = "位置",
                ["OverlayAlignment"] = "对齐",
                ["OverlayPalette"] = "配色方案",
                ["UniformColor"] = "统一颜色",
                ["ApplyToAll"] = "应用到全部",
                ["Overlay_CpuUsage"] = "CPU 使用率",
                ["Overlay_CpuTemp"] = "CPU 温度",
                ["Overlay_CpuPower"] = "CPU 功耗",
                ["Overlay_CpuClock"] = "CPU 频率",
                ["Overlay_GpuUsage"] = "GPU 使用率",
                ["Overlay_GpuTemp"] = "GPU 温度",
                ["Overlay_GpuPower"] = "GPU 功耗",
                ["Overlay_GpuClock"] = "GPU 频率",
                ["Overlay_MemUsed"] = "内存已用",
                ["Overlay_MemUsage"] = "内存使用率",
                ["Overlay_FpsDisplay"] = "显示帧率",
                ["Overlay_FpsGame"] = "游戏帧率",
                ["Overlay_NetDownload"] = "网络下载",
                ["Overlay_NetUpload"] = "网络上传",
                ["EdgeTop"] = "顶部",
                ["EdgeBottom"] = "底部",
                ["EdgeLeft"] = "左侧",
                ["EdgeRight"] = "右侧",
                ["AlignStart"] = "起始",
                ["AlignCenter"] = "居中",
                ["AlignEnd"] = "末尾",
                ["DisplayModeLabelOnly"] = "仅标签",
                ["DisplayModeIconAndValue"] = "图标+数值",
                ["PaletteNeonCyber"] = "霓虹赛博",
                ["PaletteQuantumIce"] = "量子冰蓝",
                ["PaletteSolarFire"] = "日耀烈焰",
                ["PaletteMatrixGreen"] = "矩阵绿",
                ["PalettePlasmaViolet"] = "等离子紫",
                ["PaletteTitanium"] = "钛金属",
                ["PaletteEmeraldCircuit"] = "翡翠电路",
                ["PalettePhantomRed"] = "幻影红",
                ["TrayOverlayToggle"] = "显示飘窗",
                ["TrayOverlayMetrics"] = "飘窗指标",
                ["OverlayMetricColor"] = "颜色",
                ["OverlayDisplayMode"] = "显示模式",
                ["OverlayCustomLabel"] = "自定义标签",
                ["OverlayItemSpacing"] = "间距",
                ["DisplayModeIconOnly"] = "仅图标",
                ["DisplayModeValueOnly"] = "仅数值",
                ["ApplyPalette"] = "应用配色",
                ["OverlayFontSize"] = "字体大小",
                ["OverlayBackgroundEnabled"] = "显示背景",
                ["OverlayBackgroundColor"] = "背景颜色",
                ["OverlayBackgroundOpacity"] = "背景透明度",
                ["OverlayShowIcon"] = "图标",
                ["OverlayShowLabel"] = "标签",
                ["TaskbarTab"] = "任务栏",
                ["SettingsTaskbar"] = "任务栏小组件",
                ["TaskbarWidgetEnabled"] = "启用任务栏小组件",
                ["TaskbarPosition"] = "任务栏位置",
                ["TaskbarLeftOfTray"] = "托盘左侧",
                ["TaskbarRightOfStart"] = "开始按钮右侧",
                ["TaskbarLeftmost"] = "任务栏最左侧",
                ["TaskbarRowSpacing"] = "行间距",
                ["TaskbarMaxRows"] = "行数",
                ["TrayTaskbarToggle"] = "显示任务栏小组件"
            },
            ["en-US"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["AppTitle"] = "GearGauge",
                ["MonitorTab"] = "Monitor",
                ["SettingsTab"] = "Settings",
                ["OverlayTab"] = "Overlay",
                ["Monitoring"] = "Monitoring",
                ["Settings"] = "Settings",
                ["LastUpdatedPrefix"] = "Last updated",
                ["Initializing"] = "Initializing monitor services...",
                ["MonitoringActive"] = "Monitoring is active.",
                ["InitializationFailed"] = "Initialization failed",
                ["RefreshFailed"] = "Refresh failed",
                ["LastAttempt"] = "Last attempt",
                ["Stopping"] = "Stopping monitor services...",
                ["SourcePrefix"] = "Source",
                ["Elevated"] = "Elevated",
                ["NotElevated"] = "Not elevated - some sensors unavailable",
                ["RestartAsAdmin"] = "Restart as Admin",
                ["CpuSection"] = "CPU",
                ["GpuSection"] = "GPU",
                ["MemorySection"] = "Memory",
                ["FpsSection"] = "FPS",
                ["NetworkSection"] = "Network",
                ["PerCoreMetrics"] = "Per-Core Metrics",
                ["Usage"] = "Usage",
                ["Temperature"] = "Temperature",
                ["Power"] = "Power",
                ["Clock"] = "Clock",
                ["Capacity"] = "Capacity",
                ["Used"] = "Used",
                ["Available"] = "Available",
                ["Display"] = "Display",
                ["Game"] = "Game",
                ["Active"] = "Active",
                ["DisplayName"] = "Display Name",
                ["Provider"] = "Provider",
                ["Status"] = "Status",
                ["Model"] = "Model",
                ["SettingsSampling"] = "Sampling",
                ["SettingsLanguage"] = "Language",
                ["SettingsTheme"] = "Theme",
                ["SettingsTemperatureUnit"] = "Temperature unit",
                ["SettingsGpuSelection"] = "Monitored GPU",
                ["SettingsNetworkSelection"] = "Monitored network",
                ["SettingsMetricGpuSelection"] = "GPU metric source",
                ["SettingsMetricNetworkSelection"] = "Network metric source",
                ["SettingsPercentages"] = "Percentages",
                ["SettingsTemperatures"] = "Temperatures",
                ["SettingsClocks"] = "Clocks",
                ["SettingsPowerMemory"] = "Power and Memory",
                ["SettingsNetwork"] = "Network",
                ["SampleIntervalMs"] = "Sample interval (ms)",
                ["CpuUsageDecimals"] = "CPU usage decimals",
                ["GpuUsageDecimals"] = "GPU usage decimals",
                ["MemoryUsageDecimals"] = "Memory usage decimals",
                ["CpuTemperatureDecimals"] = "CPU temperature decimals",
                ["GpuTemperatureDecimals"] = "GPU temperature decimals",
                ["CpuClock"] = "CPU clock",
                ["GpuClock"] = "GPU clock",
                ["CpuPowerDecimals"] = "CPU power decimals",
                ["GpuPowerDecimals"] = "GPU power decimals",
                ["MemoryCapacityDecimals"] = "Memory capacity decimals",
                ["NetworkSpeed"] = "Network speed",
                ["UnitLabel"] = "Unit",
                ["DecimalsLabel"] = "Decimals",
                ["Save"] = "Save",
                ["Cancel"] = "Cancel",
                ["AllDevices"] = "All",
                ["LanguageSystem"] = "System default",
                ["LanguageChinese"] = "Chinese",
                ["LanguageEnglish"] = "English",
                ["ThemeSystem"] = "Windows default",
                ["ThemeLight"] = "Light",
                ["ThemeDark"] = "Dark",
                ["TempCelsius"] = "Celsius",
                ["TempFahrenheit"] = "Fahrenheit",
                ["Download"] = "Download",
                ["Upload"] = "Upload",
                ["Core"] = "Core",
                ["ActiveState"] = "Active",
                ["IdleState"] = "Idle",
                ["Up"] = "Up",
                ["Down"] = "Down",
                ["SelectedBadge"] = "Selected",
                ["SettingsSystem"] = "System",
                ["SettingsAutoStart"] = "Auto-start on boot",
                ["SettingsCloseToTray"] = "Minimize to system tray on close",
                ["TrayShowWindow"] = "Show Main Window",
                ["TrayTaskPage"] = "Task Page",
                ["TrayExit"] = "Exit",
                ["SaveSuccess"] = "Settings saved",
                ["SettingsOverlay"] = "Overlay",
                ["OverlayEnabled"] = "Enable Overlay",
                ["OverlayEdge"] = "Position",
                ["OverlayAlignment"] = "Alignment",
                ["OverlayPalette"] = "Color Palette",
                ["UniformColor"] = "Uniform Color",
                ["ApplyToAll"] = "Apply to All",
                ["Overlay_CpuUsage"] = "CPU Usage",
                ["Overlay_CpuTemp"] = "CPU Temp",
                ["Overlay_CpuPower"] = "CPU Power",
                ["Overlay_CpuClock"] = "CPU Clock",
                ["Overlay_GpuUsage"] = "GPU Usage",
                ["Overlay_GpuTemp"] = "GPU Temp",
                ["Overlay_GpuPower"] = "GPU Power",
                ["Overlay_GpuClock"] = "GPU Clock",
                ["Overlay_MemUsed"] = "Mem Used",
                ["Overlay_MemUsage"] = "Mem Usage",
                ["Overlay_FpsDisplay"] = "Display FPS",
                ["Overlay_FpsGame"] = "Game FPS",
                ["Overlay_NetDownload"] = "Net Download",
                ["Overlay_NetUpload"] = "Net Upload",
                ["EdgeTop"] = "Top",
                ["EdgeBottom"] = "Bottom",
                ["EdgeLeft"] = "Left",
                ["EdgeRight"] = "Right",
                ["AlignStart"] = "Start",
                ["AlignCenter"] = "Center",
                ["AlignEnd"] = "End",
                ["DisplayModeLabelOnly"] = "Label Only",
                ["DisplayModeIconAndValue"] = "Icon + Value",
                ["PaletteNeonCyber"] = "Neon Cyber",
                ["PaletteQuantumIce"] = "Quantum Ice",
                ["PaletteSolarFire"] = "Solar Fire",
                ["PaletteMatrixGreen"] = "Matrix Green",
                ["PalettePlasmaViolet"] = "Plasma Violet",
                ["PaletteTitanium"] = "Titanium",
                ["PaletteEmeraldCircuit"] = "Emerald Circuit",
                ["PalettePhantomRed"] = "Phantom Red",
                ["TrayOverlayToggle"] = "Show Overlay",
                ["TrayOverlayMetrics"] = "Overlay Metrics",
                ["OverlayMetricColor"] = "Color",
                ["OverlayDisplayMode"] = "Display Mode",
                ["OverlayCustomLabel"] = "Custom Label",
                ["OverlayItemSpacing"] = "Spacing",
                ["DisplayModeIconOnly"] = "Icon Only",
                ["DisplayModeValueOnly"] = "Value Only",
                ["ApplyPalette"] = "Apply Palette",
                ["OverlayFontSize"] = "Font Size",
                ["OverlayBackgroundEnabled"] = "Show Background",
                ["OverlayBackgroundColor"] = "Bg Color",
                ["OverlayBackgroundOpacity"] = "Bg Opacity",
                ["OverlayShowIcon"] = "Icon",
                ["OverlayShowLabel"] = "Label",
                ["TaskbarTab"] = "Taskbar",
                ["SettingsTaskbar"] = "Taskbar Widget",
                ["TaskbarWidgetEnabled"] = "Enable Taskbar Widget",
                ["TaskbarPosition"] = "Position",
                ["TaskbarLeftOfTray"] = "Left of Tray",
                ["TaskbarRightOfStart"] = "Right of Start",
                ["TaskbarLeftmost"] = "Leftmost",
                ["TaskbarRowSpacing"] = "Row Spacing",
                ["TaskbarMaxRows"] = "Rows",
                ["TrayTaskbarToggle"] = "Show Taskbar Widget"
            }
        };

    public string ResolveLanguageCode(string configuredLanguage)
    {
        if (!string.Equals(configuredLanguage, LanguageModes.System, StringComparison.OrdinalIgnoreCase))
        {
            return string.Equals(configuredLanguage, LanguageModes.Chinese, StringComparison.OrdinalIgnoreCase)
                ? LanguageModes.Chinese
                : LanguageModes.English;
        }

        var systemLanguage = CultureInfo.CurrentUICulture.Name;
        return systemLanguage.StartsWith("zh", StringComparison.OrdinalIgnoreCase)
            ? LanguageModes.Chinese
            : LanguageModes.English;
    }

    public IReadOnlyDictionary<string, string> GetTexts(string configuredLanguage)
    {
        var code = ResolveLanguageCode(configuredLanguage);
        return Dictionaries[code];
    }
}
